@startuml

Class EscapeGame {
config: Config
menu(): boolean
start(): void
}

class Config {

reload(): void
}

class Log {

}

abstract class AbstractMode {
config: Config
user: AbstractUser
readCombination(): int[]
generateCombination(): int[]
start(): void
}

class ModeChallenger {
config: Config
start(): void
}

class ModeDefender {
config: Config
start(): void
}

class ModeDual {
config: Config
start(): void
}


abstract class AbstractUser {
getCombinationAsString(): String
}

class BumbAI {

}

class Human {

}


AbstractMode <|--- ModeChallenger
AbstractMode <|--- ModeDefender
AbstractMode <|--- ModeDual

AbstractUser <|--- AI
AbstractUser <|--- Human

AI <|--- BumbAI

EscapeGame -- AbstractMode
EscapeGame -- Log

EscapeGame *-- Config

AbstractMode -- AbstractUser

@enduml